### ISSUE TITLE
Unable to run Test script

### ISSUE THREAD

**Issue by Morpheus3000** [shi-jian/shapenet-intrinsics#1]
Hello,

I was trying to run your code on an input image and a masked pair. The image is a real world image that I found on the internet and manually created the mask and resized both to 256x256 jpeg. But when I try running the inference script with the following command:

`th Test.lua -input rsz_car.jpg -mask rsz_mask.jpg -model model.t7 -outdir output`

I get the following error:

```
 ~/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
~/torch/install/share/lua/5.1/nn/JoinTable.lua:39: bad argument #1 to 'copy' (sizes do not match at ~/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
stack traceback:
        [C]: in function 'copy'
        ~/torch/install/share/lua/5.1/nn/JoinTable.lua:39: in function <~/torch/install/share/lua/5.1/nn/JoinTable.lua:21>
        [C]: in function 'xpcall'
        ~/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        .../torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
        .../torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        .../torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        Test.lua:37: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        ~/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        .../torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
        .../torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        .../torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        Test.lua:37: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
```

The first time I thought it was because of the dimensions not matching for the network, as I remember Torch needing the images to be padded to a specific size for the networks. So I resized it the image according to the dimensions mentioned in the template.xml files in the render folder, which is also what is mentioned in the supplementary materials. Yet, I get the same errors. Could you please help in figuring out where I am going wrong? Thank you for your time.

**Comment by shi-jian** [comment]
@Morpheus3000 
Well, early in 2016 torch changed its API on the SpatialUpsampling layer, it would cause the problem. I have updated the download link for the trained model, please try it again.

[trained model](http://share.shijian.org.cn/shapenet/intrinsics/model.t7)

**Comment by Morpheus3000** [comment]
Thank you! It worked!

In the meantime, I was trying something with the data, for which I have opened a new issue. Hope you can help with that one!
