### ISSUE TITLE
how to render texture

### ISSUE THREAD

**Issue by ShijianXu** [shi-jian/shapenet-intrinsics#10]
Hi,

First thank you for providing the rendering scripts.  

I am new to mitsuba and it seems that the templates you provide cannot render textures for the obj. I want to render the specular highlight on the object and meanwhile render the texture. Do you know how to achieve this?

Thanks a lot.

**Comment by shi-jian** [comment]
@ShijianXu If you want to render specular with texture, you should use the template-i.xml, which renders shapenet object with texture and material properties. You should confirm that in .mtl file, the material contains correct specular parameters like:

```
Ns 1000
illum 2
```

for example, considering the car model used in this project, you can change the model.mtl file, 

```
newmtl BODY_COLOR1
Ka 0.000000 0.000000 0.000000
Kd 0.0 0.0 0.0
Ks 0.330000 0.330000 0.330000
Ns 1000
illum 2
```

to see the result.

**Comment by ShijianXu** [comment]
Thanks a lot.
