### ISSUE TITLE
Mistuba renderer precompiled dll fails on windows

### ISSUE THREAD

**Issue by Morpheus3000** [shi-jian/shapenet-intrinsics#2]
Hello,

I am trying to use the render scripts to generate the dataset on Windows. As instructed on your fork of the mistuba renderer, I put the pre-compiled windows dll in the plugins directory from your repository. However, when I run the generated render script, I get the following errors:

![image](https://user-images.githubusercontent.com/16116047/29868413-195486a2-8d7f-11e7-86d8-ccf8301061c0.png)

Could you advice on how to fix it? Or should I compile your fork of Mitsuba renderer locally?

Thank you!

**Comment by shi-jian** [comment]
@Morpheus3000 
I found the same problem. Maybe it is caused by different compiler settings? 
Could you please try to compile the renderer? I'm quite sure that would work on Win/Linux/Mac.

**Comment by Morpheus3000** [comment]
Hi! I have been trying to compile it on Windows in the meantime, but I am getting the following errors:

```
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "\mitsuba-shapenet\SConstruct", line 12, in <module>
Using configuation file "\mitsuba-shapenet\config.py"

A configuration file must be selected! Have a look at http://www.mitsuba-renderer.org/docs.html
```

My directory structure is as follows:

```
CMakeLists.txt  SConstruct  data          doc      setpath.csh  shapenet
README.md       build       dependencies  include  setpath.sh   src
```

I have the dependencies downloaded and renamed properly as you can see. I am using Visual Studio 2015. I tried running scons from MSBuild, Native Tools and Developer command prompts, but all of them give the same error. Also, it is looking for config.py, which doesn't exists in the directory. The documentation on Mitsuba renderer just says VS2010. Is it not possible to use 2015?

I am also going to try installing on Ubuntu 16.04. I will update the results from there too. I don't have access to a Mac, so can't check that.

Thanks!

UPDATE: I just tried it on my Linux, it still looks for a config.py and so fails.

UPDATE 2: I renamed config-linux-gcc.py from the build directory to config.py, but now it can't find QTOpenGL. I have opengl5 from Anaconda's python distribution.

**Comment by shi-jian** [comment]
@Morpheus3000 
For compiling mitsuba on Windows, you might need VS2013, since they provide dependency libraries of VS2013. Try to use CMake on windows, that might works.

On ubuntu 16.04, you should install dependency libraries. In mitsuba documents:

> sudo apt-get install build-essential scons mercurial qt4-dev-tools libpng12-dev
libjpeg-dev libilmbase-dev libxerces-c-dev libboost-all-dev libopenexr-dev
libglewmx-dev libxxf86vm-dev libpcrecpp0 libeigen3-dev libfftw3-dev

**Comment by Morpheus3000** [comment]
I tried using CMake on Windows. But when the make process fails with the following error message:

 E:\mitsuba\build2\src\librender\mitsuba-render_pch\mitsuba_precompiled_stub.cpp : fatal error C1083: Cannot open include file: 'mitsuba_precompiled.hpp;': No such file or directory [E:\mitsuba\build2\src\librender\mitsuba-render.vcxpro j]

I looked for the mitsuba_precompiled.hpp file and it is present under the directory data\pch, yet the program doesnot pick it up

**Comment by shi-jian** [comment]
@Morpheus3000 

That is exact problem I met on Windows, so I some word in the readme of [mitsuba-shapenet](https://github.com/shi-jian/mitsuba-shapenet).

> If you meet the problem of missing header such as mitsuba_precompiled_header.hpp, please turn off MTS_USE_PCH flag during CMake.

I think I should highlight it:)

**Comment by Morpheus3000** [comment]
Ah, sorry that is indeed a miss on my part. I did not consult the readme there. I changed the option and it compiled without any problem! I just tried the scripts too and they work without any problem! 

Thanks!
