### ISSUE TITLE
Depth extraction

### ISSUE THREAD

**Issue by ibcny** [shi-jian/shapenet-intrinsics#3]
Hi,

I'm exactly using the given xml file(template-d.xml ) to extract depth images from the shapenet v2 object models. However, the output is not a depth map but always a black and white image with slightly smoothed edges.

Do you have any recommendations to resolve this issue? 

Thanks.

**Comment by Morpheus3000** [comment]
If you use the synthesize.bat file, it will convert the depth image to a mask, using imagemagick. If you just want the depth images, you can find them as <number>_d.exr

You can probably try changing the format to jpg from exr raster using the following:

`magick mogrify -format jpg 0001_d.exr`

Disclaimer: I just took this from the synthesize.bat script which converts the images from HDR to jpg to save size (it's mentioned in the docs). Only the depth HDR is converted to a mask by switching off the alpha channel, so it becomes a logical image instead.

**Comment by ibcny** [comment]
I am sorry, I misexplained how I extracted the depth data. I do not use the synthesize.bat script but indeed, I use the template-d.xml file given, modifying the camera parameter from HDR to LDR. Then I use the command line interface of mitsuba to extract depth images. Below is the xml file I use to extract depth maps:

`
<?xml version="1.0" encoding="utf-8"?>

<scene version="0.5.0">
	
    <shape type="shapenet">
        <string name="filename" value="$model" />
    </shape>

    <emitter type="constant" />

    <integrator type="field">
		<string name="field" value="distance" />
		<spectrum name="undefined" value="0" />
	</integrator>

    <sensor type="perspective">
        <transform name="toWorld">
            <lookAt target="0,0,0" origin="$view" up="0,1,0"/>
        </transform>

        <sampler type="ldsampler">
            <integer name="sampleCount" value="16"/>
        </sampler>

        <film type="ldrfilm">
            <integer name="width" value="256"/>
            <integer name="height" value="256"/>
            <boolean name="banner" value="false"/>
			<boolean name="attachLog" value="false"/>
        </film>
    </sensor>
</scene>
`

Thanks.

**Comment by shi-jian** [comment]
@phanax 

the 'distance' integrator would give you the distance from your camera to the surface point. If you use LDR output, the value will be clamped to 1.0.

I think models in ShapeNet are normalized to a unit bounding box. Usually I put the camera on a sphere with radius 2.0 to render those objects, so the distance from camera to the object often > 1.0.

You can use HDR image, and scale the output image if necessary.
