### ISSUE TITLE
Unable to download environment maps

### ISSUE THREAD

**Issue by mbanani** [shi-jian/shapenet-intrinsics#9]
Hi, 

Thanks a lot for sharing your code. I was unable to download the environment maps for (
http://share.shijian.org.cn/shapenet/intrinsics/envmap.zip). Is there a new location where I can download this map from? 

Thank you,
Mohamed

**Comment by shi-jian** [comment]
@mbanani 

The VPS is out dated. I have uploaded the models and envmaps to OneDrive.
https://1drv.ms/f/s!ApfQp_rip6el-X-neX32NGAE_aiC

There are two versions, the model_old.t7 is trained on an relative old version of torch, maybe around Oct. 2016.
And torch changed their API for upsampling layer, so the model.t7 is trained on a version around Feb. 2017.
I heard that torch is not upgrading now, and I’m not sure whether new version can still support old models.

**Comment by mbanani** [comment]
Thank you very much for your quick response!
